# -*- coding: utf-8 -*-
"""project4_Pseudorange_vs_Carrier-Phase_Comparison.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bBLrk7dqecC5d8x45xj9oOTAH-sHEyi0

=============================================================================
🛰️ Project 4 — Pseudorange vs Carrier-Phase Comparison
=============================================================================
 Author   : Hakim El Azzouzi
 Degree   : MSc Global Navigation Satellite Systems
            Mohammed First University, Oujda, Morocco
 Email    : elazzouzihakim10@gmail.com
 LinkedIn : https://linkedin.com/in/Hakim-El-Azzouzi
 Location : Luxembourg 🇱🇺
-----------------------------------------------------------------------------
 Station  : AUCK00NZL  —  Auckland, New Zealand  (GeoNet / LINZ Network)
 File     : AUCK00NZL_R_20260010000_01D_30S_MO.rnx
 Receiver : TRIMBLE ALLOY
 Antenna  : TRM115000.00
 Format   : RINEX 3.05  |  Mixed Constellations  |  30-second sampling
 Date     : 2026-01-01  (Day-of-Year 001)
-----------------------------------------------------------------------------
 Description
 -----------
Every GNSS receiver produces **two fundamentally different range measurements** at every epoch:

| Observable | Symbol | Precision | Drawback |
|-----------|--------|-----------|----------|
| **Pseudorange** | `C1C` / `C1X` | ~1–3 metres | Noisy — multipath, thermal noise |
| **Carrier phase** | `L1C` / `L1X` | ~2–3 mm | Contains unknown integer ambiguity N |

This project compares them directly for a GPS satellite over 24 hours, using 3 plots:

1. 📡 **Raw measurements overlaid** — pseudorange and carrier-phase on the same scale
2. 📉 **Noise comparison** — epoch-to-epoch differences (code noise vs phase noise)
3. 🔢 **Code minus phase (C - Φ)** — the difference reveals the integer ambiguity + ionospheric delay

---

## 📐 The Mathematics

### Pseudorange equation:
```
P = ρ + c·(dT - dt) + I + T + ε_P
```

### Carrier-phase equation (converted to metres):
```
Φ = ρ + c·(dT - dt) - I + T + λ·N + ε_Φ
```

### Code minus Phase (C - Φ):
```
P - Φ = 2·I + λ·N + (ε_P - ε_Φ)
      ≈ 2·I + λ·N         (since ε_P >> ε_Φ)
```
Where:
- `ρ` = true geometric range (receiver to satellite)
- `c` = speed of light (299,792,458 m/s)
- `dT` = receiver clock offset
- `dt` = satellite clock offset
- `I` = ionospheric delay (**+** for code, **−** for phase)
- `T` = tropospheric delay
- `λ` = carrier wavelength (L1 ≈ 0.1903 m)
- `N` = integer phase ambiguity (unknown whole number of cycles)
- `ε_P`, `ε_Φ` = measurement noise

### Key insight:
> Even though we do **not know N** (the integer ambiguity), we can still compare
> pseudorange and carrier-phase because `P - Φ` is **nearly constant** over time
> (as long as there is no cycle slip). Changes in `P - Φ` reveal the ionosphere.

---
-----------------------------------------------------------------------------
 **About the projects**
 ----------------------
# Step1: Install & Import Libraries
# Step2: Load the RINEX File
# Step3: Select Satellite and Extract Observables
# Step4: Plot 1: Raw Measurements Overlaid
# Step5: Plot 2: Noise Comparison (Epoch-to-Epoch Differences)
# Step6: Plot 3: Code Minus Phase (C - Φ)
=============================================================================
"""

pip install --upgrade georinex

# ──────────────────────────────────────────────────────────
# Step 1 — Install & Import Libraries
# ──────────────────────────────────────────────────────────
# Install georinex if not already installed
# Uncomment the line below if you are running this for the first time:
# !pip install --upgrade georinex

import georinex as gr
import xarray as xr
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from matplotlib.colors import LinearSegmentedColormap
import warnings

warnings.filterwarnings('ignore')  # suppress xarray FutureWarnings during load

# Global plot style (dark GNSS theme)
plt.rcParams.update({
    'figure.dpi': 120,
})

print('✅ All libraries loaded successfully')
print(f'   georinex version : {gr.__version__}')
print(f'   xarray version   : {xr.__version__}')

# ─────────────────────────────────────────────────────────────────
# Step 2 — Load the RINEX File
# ─────────────────────────────────────────────────────────────────
# RINEX FILE PATH HERE
obs_path = "/AUCK00NZL_R_20260010000_01D_30S_MO.rnx"  # ← change this path
# Read the file header first (fast — no data loaded yet)
print("📋 FILE HEADER")
print("=" * 60)
header = gr.rinexheader(obs_path)

for key, value in header.items():
    print(f"{key:<25}: {value}")

print()

# Load all observation data (interval=30 means keep 30-sec rate)

print("⏳ Loading observation data (this may take 1–2 minutes)...")
obs = gr.load(obs_path, interval=30)
print()
print("✅ Data loaded!")
print(obs)

# ─────────────────────────────────────────────────
# Step 3 — Select Satellite and Extract Observables
# ─────────────────────────────────────────────────
# WE MANUALLY SET A SATELLITE HERE, OR LEAVE AS 'auto'

SAT = 'auto'   # ← set to e.g. 'G29' to use a specific satellite

C  = 299_792_458.0    # speed of light [m/s]  — exact, by definition
F1 = 1_575.42e6       # GPS L1 frequency [Hz] — exact, from GPS ICD
F2 = 1_227.60e6       # GPS L2 frequency [Hz] — exact, from GPS ICD

LAM_L1 = C / F1
LAM_L2 = C / F2

# Auto-select: find GPS satellite with most L1 + L2 valid data
gps_sats = sorted([s for s in obs.sv.values if s.startswith('G')])

if SAT == 'auto':
    best_sat = None
    best_count = 0
    for sat in gps_sats:
        try:
            n = obs['C1C'].sel(sv=sat).to_series().notna().sum()
            has_L2 = 'L2W' in obs.data_vars and obs['L2W'].sel(sv=sat).to_series().notna().sum() > 10
            if n > best_count and has_L2:
                best_count = n
                best_sat = sat
        except Exception:
            pass
    SAT = best_sat if best_sat else gps_sats[0]
    print(f"✅ Auto-selected satellite: {SAT} ({best_count} valid C1C epochs)")
else:
    print(f"✅ Using manually selected satellite: {SAT}")

# Extract: Pseudorange C1C [metres]

pr = obs['C1C'].sel(sv=SAT).to_series().dropna()

# Extract: Carrier phase L1C [cycles] → convert to metres
# Multiply by L1 wavelength to get metres
cp_L1 = obs['L1C'].sel(sv=SAT).to_series().dropna() * LAM_L1

# Extract: Carrier phase L2W [cycles] → convert to metres (if available)
cp_L2 = None
if 'L2W' in obs.data_vars:
    cp_L2 = obs['L2W'].sel(sv=SAT).to_series().dropna() * LAM_L2

# Align pseudorange and L1 carrier phase to common timestamps
common = pr.index.intersection(cp_L1.index)
pr     = pr[common]
cp_L1  = cp_L1[common]

# ─────────────────────────────────────────────────────────────────
# Compute Code minus Phase (C - Φ)
#
# P - Φ = 2·I + λ·N + noise
#
# Even without knowing N (the integer ambiguity),
# the DIFFERENCE over time shows ionospheric variation.
# The level (DC offset) contains λ·N which we cannot resolve here.
# ─────────────────────────────────────────────────────────────────
code_minus_phase = pr - cp_L1

print()
print(f"LAM_L1 = {LAM_L1:.15f} m  ≈  {LAM_L1*100:.4f} cm")
print(f"LAM_L2 = {LAM_L2:.15f} m  ≈  {LAM_L2*100:.4f} cm")
print()
print(f"📊 Observable statistics for {SAT}:")
print(f"   Common epochs (C1C ∩ L1C) : {len(common)}")
print()
print(f"   Pseudorange  C1C  min: {pr.min()/1e6:.3f} Mm   max: {pr.max()/1e6:.3f} Mm")
print(f"   Carrier Ph.  L1C  min: {cp_L1.min()/1e6:.3f} Mm   max: {cp_L1.max()/1e6:.3f} Mm")
print()
print(f"   Code − Phase (P − Φ):")
print(f"     Mean  : {code_minus_phase.mean():,.3f} m  ← contains λ·N (integer ambiguity term)")
print(f"     Std   : {code_minus_phase.std():.3f} m    ← reflects code noise + ionosphere")
print(f"     Min   : {code_minus_phase.min():,.3f} m")
print(f"     Max   : {code_minus_phase.max():,.3f} m")
print()
print(f"💡 The mean of (P − Φ) ≈ 2·I + λ·N")
print(f"   We cannot separate I and N without a second frequency.")
print(f"   But changes in (P − Φ) over time ≈ ionospheric variation (2·ΔI).")

# ──────────────────────────────────────────
# Step 4 — Plot 1: Raw Measurements Overlaid
# ──────────────────────────────────────────
# Shift carrier phase to match pseudorange mean
# This removes the arbitrary λ·N offset and aligns the curves
offset = pr.mean() - cp_L1.mean()
cp_shifted = cp_L1 + offset

# Colours
COLOR_CODE  = "#1E88E5"   # blue  → pseudorange (noisy code)
COLOR_PHASE = "#43A047"   # green → carrier phase (precise)

# Figure
fig, ax = plt.subplots(figsize=(16, 6), facecolor="#0d1117")
ax.set_facecolor("#111827")

ax.set_title(
    f'Pseudorange vs Carrier Phase — GPS {SAT} | AUCK00NZL | 2026-01-01\n'
    'Both measure the same geometric range — carrier phase is shifted by λ·N to align',
    fontsize=13, fontweight='bold', color="#ffffff"
)

# Plot pseudorange
ax.plot(
    pr.index, pr.values / 1e6,
    color=COLOR_CODE, lw=1.8, alpha=0.9,
    label='Pseudorange C1C  — code measurement  (~1–3 m noise)'
)

# Plot carrier phase (shifted)
ax.plot(
    cp_shifted.index, cp_shifted.values / 1e6,
    color=COLOR_PHASE, lw=1.2, alpha=0.9,
    label=f'Carrier Phase L1C  — phase measurement  (~3 mm noise)  [shifted by {offset/1e6:.4f} Mm = λ·N]'
)

# If we zoom in it shows the noise — add a zoom inset
# Show a 30-minute window around the peak elevation
idx_min = pr.idxmin()
zoom_start = idx_min - pd.Timedelta('15min')
zoom_end   = idx_min + pd.Timedelta('15min')

pr_zoom = pr[zoom_start:zoom_end]
cp_zoom = cp_shifted[zoom_start:zoom_end]

if len(pr_zoom) > 3:
    # Create inset axes
    axins = ax.inset_axes([0.02, 0.05, 0.28, 0.38])   # [left, bottom, width, height]
    axins.set_facecolor("#0d1b2a")

    axins.plot(pr_zoom.index,  pr_zoom.values / 1e6,
               color=COLOR_CODE,  lw=1.2, alpha=0.9)
    axins.plot(cp_zoom.index,  cp_zoom.values / 1e6,
               color=COLOR_PHASE, lw=1.0, alpha=0.9)

    axins.set_title('Zoom: 30 min at peak elevation', fontsize=7, color="#aaaaaa")
    axins.tick_params(colors="#aaaaaa", labelsize=6)
    axins.xaxis.set_major_formatter(mdates.DateFormatter('%H:%M'))
    for spine in axins.spines.values():
        spine.set_edgecolor("#444444")
    axins.grid(True, color="#222222", linewidth=0.4)

ax.set_ylabel('Range [Mm = million metres]', fontsize=11, color="#aaaaaa")
ax.set_xlabel('UTC Time (HH:MM)', fontsize=11, color="#aaaaaa")
ax.tick_params(colors="#aaaaaa")
ax.grid(True, color="#222222", linewidth=0.5)

for spine in ax.spines.values():
    spine.set_edgecolor("#333333")

ax.xaxis.set_major_formatter(mdates.DateFormatter('%H:%M'))
ax.xaxis.set_major_locator(mdates.HourLocator(interval=2))
plt.xticks(rotation=30, color="#aaaaaa")

legend = ax.legend(
    fontsize=9, loc='upper right',
    framealpha=0.3, facecolor="#1a1a2e", edgecolor="#444444"
)
for text in legend.get_texts():
    text.set_color("white")

plt.tight_layout()
plt.savefig('plot1_pseudorange_vs_carrier_phase.png', dpi=150,
            bbox_inches='tight', facecolor=fig.get_facecolor())
plt.show()

print('✅ Plot saved: plot1_pseudorange_vs_carrier_phase.png')
print()
print('💡 Interpretation:')
print('   • Both curves trace the same orbital arc — same satellite, same geometry')
print('   • Carrier phase appears smoother (nearly invisible noise at this scale)')
print('   • Pseudorange has visible scatter (~1–3 m noise level)')
print('   • The constant shift between them = λ·N (the integer ambiguity in metres)')
print(f'   • Applied shift = {offset:.3f} m  ≈  {offset/LAM_L1:.0f} L1 wavelengths')

# ──────────────────────────────────────────────────────────────
# Step 5 — Plot 2: Noise Comparison (Epoch-to-Epoch Differences)
# ──────────────────────────────────────────────────────────────
# Epoch-to-epoch differences

pr_diff   = pr.diff().dropna()      # pseudorange variation between epochs
cp_diff   = cp_L1.diff().dropna()   # carrier phase variation between epochs

pr_noise_std  = pr_diff.std()
cp_noise_std  = cp_diff.std()
noise_ratio   = pr_noise_std / cp_noise_std

print(f"Pseudorange  epoch noise (std of Δ) : {pr_noise_std:.4f} m")
print(f"Carrier phase epoch noise (std of Δ): {cp_noise_std*100:.4f} cm")
print(f"Noise ratio code/phase               : {noise_ratio:.0f}×  — phase is {noise_ratio:.0f}× less noisy")

# Figure: two panels sharing the time axis

fig, axes = plt.subplots(2, 1, figsize=(16, 8), sharex=True, facecolor="#0d1117")
fig.suptitle(
    f'Epoch-to-Epoch Noise: Pseudorange vs Carrier Phase — GPS {SAT}\n'
    'Differences between consecutive 30-second epochs reveal measurement noise',
    fontsize=13, fontweight='bold', color="#ffffff"
)

for ax in axes:
    ax.set_facecolor("#111827")
    ax.tick_params(colors="#aaaaaa")
    ax.grid(True, color="#222222", linewidth=0.5)
    for spine in ax.spines.values():
        spine.set_edgecolor("#333333")

# ─── Panel 1: Pseudorange noise ───
axes[0].plot(pr_diff.index, pr_diff.values,
             color=COLOR_CODE, lw=0.8, alpha=0.85)
axes[0].fill_between(pr_diff.index, pr_diff.values,
                     color=COLOR_CODE, alpha=0.15)
axes[0].axhline(0,  color="#555555", lw=0.8, ls='--')
axes[0].axhline(+pr_noise_std, color=COLOR_CODE, lw=1.0, ls=':', alpha=0.7,
                label=f'+1σ = {pr_noise_std:.3f} m')
axes[0].axhline(-pr_noise_std, color=COLOR_CODE, lw=1.0, ls=':', alpha=0.7,
                label=f'−1σ = {pr_noise_std:.3f} m')

axes[0].set_ylabel('ΔPseudorange [m / epoch]', color="#aaaaaa", fontsize=11)
axes[0].set_title(
    f'Code noise  C1C  |  σ = {pr_noise_std:.3f} m  (~{pr_noise_std*100:.0f} cm RMS per epoch)',
    fontsize=10, color="#ffffff"
)
axes[0].set_ylim(-15, 15)

legend0 = axes[0].legend(fontsize=9, framealpha=0.3,
                          facecolor="#1a1a2e", edgecolor="#444444")
for t in legend0.get_texts(): t.set_color("white")

# ─── Panel 2: Carrier phase noise ───
axes[1].plot(cp_diff.index, cp_diff.values * 100,   # convert to cm
             color=COLOR_PHASE, lw=0.8, alpha=0.85)
axes[1].fill_between(cp_diff.index, cp_diff.values * 100,
                     color=COLOR_PHASE, alpha=0.15)
axes[1].axhline(0, color="#555555", lw=0.8, ls='--')
axes[1].axhline(+cp_noise_std*100, color=COLOR_PHASE, lw=1.0, ls=':', alpha=0.7,
                label=f'+1σ = {cp_noise_std*100:.2f} cm')
axes[1].axhline(-cp_noise_std*100, color=COLOR_PHASE, lw=1.0, ls=':', alpha=0.7,
                label=f'−1σ = {cp_noise_std*100:.2f} cm')

# Detect cycle slips: large jumps in phase differences
cycle_slip_threshold = 5 * cp_noise_std  # 5-sigma threshold
slips = cp_diff[np.abs(cp_diff) > cycle_slip_threshold]
if len(slips) > 0:
    axes[1].scatter(slips.index, slips.values * 100,
                    color="#F44336", s=60, zorder=5,
                    label=f'Cycle slip candidate ({len(slips)} detected)')

axes[1].set_ylabel('ΔCarrier Phase [cm / epoch]', color="#aaaaaa", fontsize=11)
axes[1].set_xlabel('UTC Time (HH:MM)', color="#aaaaaa", fontsize=11)
axes[1].set_title(
    f'Phase noise  L1C  |  σ = {cp_noise_std*100:.2f} cm  —  {noise_ratio:.0f}× less noisy than pseudorange',
    fontsize=10, color="#ffffff"
)

legend1 = axes[1].legend(fontsize=9, framealpha=0.3,
                          facecolor="#1a1a2e", edgecolor="#444444")
for t in legend1.get_texts(): t.set_color("white")

axes[1].xaxis.set_major_formatter(mdates.DateFormatter('%H:%M'))
axes[1].xaxis.set_major_locator(mdates.HourLocator(interval=2))
plt.xticks(rotation=30, color="#aaaaaa")

plt.tight_layout(rect=[0, 0, 1, 0.95])
plt.savefig('plot2_noise_comparison.png', dpi=150,
            bbox_inches='tight', facecolor=fig.get_facecolor())
plt.show()

print('✅ Plot saved: plot2_noise_comparison.png')
print()
print('💡 Interpretation:')
print(f'   • Y-axis SCALES ARE DIFFERENT: code is in metres, phase is in centimetres')
print(f'   • Code noise  σ ≈ {pr_noise_std:.2f} m    → typical for pseudorange')
print(f'   • Phase noise σ ≈ {cp_noise_std*100:.2f} cm  → millimetre-level precision')
print(f'   • Ratio: phase is {noise_ratio:.0f}× less noisy than code')
if len(slips) > 0:
    print(f'   • Red dots = cycle slip candidates (signal interrupted, counter reset)')

# ─────────────────────────────────────────────────────────────────────
# Step 6 — Plot 3: Code Minus Phase (P − Φ)
# ─────────────────────────────────────────────────────────────────────
COLOR_DIFF = "#8E24AA"   # purple → derived combination

# ─────────────────────────────────────────────
# Detrended P - Φ  (remove mean to focus on variations)
# The mean contains λ·N which is arbitrary
# ─────────────────────────────────────────────
cmp_mean    = code_minus_phase.mean()
cmp_detrend = code_minus_phase - cmp_mean   # ≈ 2·ΔI  (ionospheric variation)

# ─────────────────────────────────────────────
# Figure: 2 panels
# Top   = raw P − Φ (with the λ·N offset)
# Bottom = detrended (isolates ionospheric variation)
# ─────────────────────────────────────────────
fig, axes = plt.subplots(2, 1, figsize=(16, 9), sharex=True, facecolor="#0d1117")
fig.suptitle(
    f'Code Minus Phase  (P − Φ)  —  GPS {SAT} | AUCK00NZL | 2026-01-01\n'
    'P − Φ = 2·I + λ·N + noise  —  constant level = ambiguity, variations = ionosphere',
    fontsize=13, fontweight='bold', color="#ffffff"
)

for ax in axes:
    ax.set_facecolor("#111827")
    ax.tick_params(colors="#aaaaaa")
    ax.grid(True, color="#222222", linewidth=0.5)
    for spine in ax.spines.values():
        spine.set_edgecolor("#333333")

# ─── Panel 1: Raw P − Φ ───────────────────────────────────
axes[0].plot(code_minus_phase.index, code_minus_phase.values,
             color=COLOR_DIFF, lw=1.3, alpha=0.9,
             label='P − Φ  (raw)')

axes[0].axhline(cmp_mean, color="#FFEB3B", ls='--', lw=1.2,
                label=f'Mean = {cmp_mean:.2f} m  ≈  2·I + λ·N')

# Annotate what the mean represents
n_cycles_approx = cmp_mean / LAM_L1
axes[0].annotate(
    f'Mean ≈ {cmp_mean:.1f} m\n≈ {n_cycles_approx:.0f} L1 cycles\n(contains λ·N)',
    xy=(code_minus_phase.index[len(code_minus_phase)//2], cmp_mean),
    xytext=(30, 30), textcoords='offset points',
    color="#FFEB3B", fontsize=9,
    arrowprops=dict(arrowstyle='->', color="#FFEB3B")
)

axes[0].set_ylabel('P − Φ  [m]', color="#aaaaaa", fontsize=11)
axes[0].set_title(
    'P − Φ = 2·I + λ·N  |  Level dominated by integer ambiguity λ·N',
    fontsize=10, color="#ffffff"
)

legend0 = axes[0].legend(fontsize=9, framealpha=0.3,
                          facecolor="#1a1a2e", edgecolor="#444444")
for t in legend0.get_texts(): t.set_color("white")

# ─── Panel 2: Detrended P − Φ (ionospheric variations) ────
axes[1].plot(cmp_detrend.index, cmp_detrend.values,
             color="#00BCD4", lw=1.3, alpha=0.9,
             label='(P − Φ) − mean  ≈  2·ΔI  (ionospheric variation)')

axes[1].fill_between(cmp_detrend.index, cmp_detrend.values,
                     color="#00BCD4", alpha=0.1)

axes[1].axhline(0, color="#555555", lw=0.8, ls='--')

# Shade positive values (ionospheric increase) vs negative (decrease)
axes[1].fill_between(cmp_detrend.index, cmp_detrend.values, 0,
                     where=(cmp_detrend.values > 0),
                     color="#F44336", alpha=0.15,
                     label='Ionospheric delay increasing')
axes[1].fill_between(cmp_detrend.index, cmp_detrend.values, 0,
                     where=(cmp_detrend.values < 0),
                     color="#4CAF50", alpha=0.15,
                     label='Ionospheric delay decreasing')

axes[1].set_ylabel('(P − Φ) − mean  [m]', color="#aaaaaa", fontsize=11)
axes[1].set_xlabel('UTC Time (HH:MM)', color="#aaaaaa", fontsize=11)
axes[1].set_title(
    '(P − Φ) detrended  ≈  2·ΔI  |  Slow variations = ionospheric delay changes',
    fontsize=10, color="#ffffff"
)

legend1 = axes[1].legend(fontsize=9, framealpha=0.3,
                          facecolor="#1a1a2e", edgecolor="#444444")
for t in legend1.get_texts(): t.set_color("white")

axes[1].xaxis.set_major_formatter(mdates.DateFormatter('%H:%M'))
axes[1].xaxis.set_major_locator(mdates.HourLocator(interval=2))
plt.xticks(rotation=30, color="#aaaaaa")

plt.tight_layout(rect=[0, 0, 1, 0.95])
plt.savefig('plot3_code_minus_phase.png', dpi=150,
            bbox_inches='tight', facecolor=fig.get_facecolor())
plt.show()

print('✅ Plot saved: plot3_code_minus_phase.png')
print()
print('💡 Interpretation:')
print('   • Top panel   : raw P − Φ — the flat level ≈ λ·N (ambiguity, cannot be removed here)')
print('   • Bottom panel: after removing mean — slow variation ≈ 2·ΔI (ionospheric delay)')
print(f'   • Mean (P − Φ) = {cmp_mean:.2f} m  ≈  {n_cycles_approx:.0f} L1 wavelengths')
print('   • The ambiguity N is an integer — resolving it exactly is called "ambiguity resolution"')
print('     and is what enables centimetre-level RTK positioning.')

